---
name: trigger-lambda-main
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
    - main
jobs:
  trigger-lambda:
    name: Trigger Lambda
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: |
          echo "Hi there"
      - name: Checkout
        uses: actions/checkout@master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Copy files to S3 bucket
        run: |
          aws s3 sync src s3://${{ secrets.AWS_S3_BUCKET }}
      - name: Invoke a Lambda function
        run: |
          aws lambda invoke --function-name ${{ secrets.AWS_LAMBDA_ARN }} output.log
