name: validate-yaml-pr
on:
  pull_request:
    branches:
    - main
jobs:
  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Validate YAML
      uses: brittonhayes/validate-yaml@main
      with:
        schemaPath: 'schema/schema.json'
        files: |
          src/template.yml
          src/template.yaml
